ControlFile: "SWB_MV_original.ctl"
InputTable: "MVLookup_NLCD.txt"
nx: 1182
ny: 768
modelDir: "SWB"
startdate: "2015-01-01"
enddate: "2100-12-31"
RCP: ["SSP245"]  #["SSP585", "SSP245"] 

models: ['ACCESS-CM2']  #, 'ACCESS-ESM1-5', 'AWI-CM-1-1-MR', 'BCC-CSM2-MR', 'CanESM5', 
         #'CNRM-CM6-1', 'CNRM-ESM2-1', 'EC-Earth3-Veg', 
         # 'FGOALS-g3', 'GFDL-CM4', 'GFDL-ESM4', 'HadGEM3-GC31-LL', 
         # 'INM-CM4-8', 'INM-CM5-0', 'IPSL-CM6A-LR', 'KACE-1-0-G', 'MIROC6', 'MPI-ESM1-2-HR', 
         # 'MPI-ESM1-2-LR', 'MRI-ESM2-0', 'NorESM2-LM', 'NorESM2-MM']
variables: ['net_infiltration'] #, 'actual_et', 'gross_precipitation', 'rejected_net_infiltration', 'interception', 'runon', 'runoff_outside']
